version: '3.8'

services:
  appjava:
    build: .
    container_name: balance-app
    volumes:
      - .:/app
    ports:
      - 3003:8080

  mysql:
    image: mysql:5.7
    container_name: mysql_balance
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: balance
      MYSQL_PASSWORD: root
    # ports:
    #   - 3307:3306
    expose:
      - 3306
    volumes:
      - .docker/mysql:/var/lib/mysql